package model;

public enum RequestType {
    REGISTRATION,
    SALARY,
    OPEN_ACCOUNT,
    REMOVE_ACCOUNT,
    ENROLL_COMPANY,
    DROP_COMPANY,
    SALARY_PROJECT,
    BLOCK_ACCOUNT,
    UNBLOCK_ACCOUNT,
    TRANSACTION
}
